apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k6
  namespace: k6
spec:
  selector:
    matchLabels:
      app: k6
  serviceName: "k6-load-generator"
  replicas: 1
  template:
    metadata:
      labels:
        app: k6
        test: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: "In"
                  values: [ "k6" ]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: k6
        image: quay.io/rdpanek/k6:1.0.3
        env:
        - name: GIT_REVISION
          value: "5d00086"
        - name: TEST_PLAN_NAME
          value: "baseline.js"
        - name: GIT_TEST_REPOSITORY
          valueFrom:
            configMapKeyRef:
              name: k6-config
              key: git.test.repository
        - name: ENV_PRINT
          value: "allow"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        imagePullPolicy: "Always"