apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: rdpanek/k6:0.26.2
            env:
            - name: SERVER
              value: "64.227.117.177"
            - name: PORT
              value: "9200"
            resources:
              requests:
                memory: "300Mi"
                cpu: "200m"
              limits:
                memory: "400Mi"
                cpu: "300m"
            imagePullPolicy: "Always"
          restartPolicy: "Never"